const fs = require('fs');
const cp = require('child_process');

const result = cp.execSync('node scripts/report-core.js', { encoding: 'utf8', maxBuffer: 1024 * 1024 * 10 });
const data = JSON.parse(result);

const targets = [];
for (const style of data.styles) {
    if (style.qualityScore < 0.90 || style.fidelityScore < 0.95) {
        try {
            const content = fs.readFileSync(`styles/${style.name}.yaml`, 'utf8');
            if (content.includes('# Generated by CSLN Migration Workflow')) {
                targets.push({
                    name: style.name,
                    fidelity: style.fidelityScore,
                    sqi: style.qualityScore
                });
            }
        } catch (e) {
            console.error(e.message);
        }
    }
}
targets.sort((a, b) => b.fidelity - a.fidelity || b.sqi - a.sqi);
console.log(JSON.stringify(targets, null, 2));
